analyzer:
  errors:
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    use_super_parameters: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false